cd hw3
make 1>/dev/null 2>/dev/null
./run examples/test1.k-
echo ''
./run examples/test2.k-
echo ''
./run examples/test3.k-
echo ''
./run examples/test4.k-
echo ''
./run examples/test5.k-
echo ''
./run examples/test6.k-
echo ''
./run examples/test7.k-
echo ''
./run examples/test8.k-
echo ''
./run examples/test9.k-
echo ''
./run examples/test10.k-
echo ''
./run examples/kcm.k-
echo ''
